### ISSUE TITLE
Deprecate this?

### ISSUE THREAD

**Issue by nickdunn** [symphonycms/email_field#2]
Not sure how many people use this field. It seems like its only purpose is to validate an email input (which a Text Input can do anyway), and to output a hash of the address, for things like gravatar support. Nils' Output Field (actively maintained) achieves this. Do we need both?

https://github.com/nilshoerrmann/output_field

**Comment by nickdunn** [comment]
Bump.

**Comment by nickdunn** [comment]
http://symphonyextensions.com/extensions/output_field/

**Comment by brendo** [comment]
No I don't think so, deprecation sounds like a good idea. Will release an update for 2.3, but marked as deprecated and point to the Output Field repo :)

**Comment by nickdunn** [comment]
Why bother updating for 2.3 if it's deprecated? Kill it now.

**Comment by brendo** [comment]
Well @tonyarnold had already done the PR, so the work was already done ;)

**Comment by tonyarnold** [comment]
I only use this extension for the hash that it includes in the presented data. It's useful for retrieving gravatars.
